[package]
name = "rich-presence-wrapper"
version = "0.1.0"
edition = "2024"
description = """
Discord rich presence wrapper.
"""
homepage = "https://github.com/threadexio/rich-presence-wrapper"

[features]
default = [
  "helix",
  "zed",
  "mpris-bridge",
  "lsp"
]

helix = []
zed = []
mpris-bridge = [
  "dep:fxhash",
  "dep:html-escape",
  "dep:rune",
  "dep:serde_json",
  "tokio/io-util"
]
lsp = [
  "dep:tower-lsp",
  "dep:urlencoding",
  "tokio/io-std",
]

[dependencies]
clap = { version = "4.6.0", features = ["derive", "env"] }
dirs = { version = "6" }
discord-rich-presence = { version = "1.1.0" }
eyre = { version = "0.6" }
fxhash = { version = "0.2", optional = true }
html-escape = { version = "0.2", optional = true }
magic-args = { version = "0.1" }
module = { version = "0.3", features = ["derive", "serde"] }
module-util = { version = "0.3", features = ["serde"] }
regex = { version = "1" }
rune = { version = "0.14", optional = true }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
tokio = { version = "1", features = ["macros", "sync", "time", "process", "rt"] }
toml = { version = "1" }
tower-lsp = { version = "0.20", optional = true }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }
urlencoding = { version = "2.1", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
darwin-libproc = { git = "https://git.31c0.org/a-reynbaw/darwin-libproc.git", rev = "2f131f4ed0934a8a41299aa421b75256f7b7dc58" }

